= Preferências Compartilhadas (Shared Preferences)

Segundo a Google Developers (2020) "Um objeto SharedPreferences indica um arquivo que contém pares de chave-valor e fornece métodos simples para leitura
e gravação. Cada arquivo SharedPreferences é gerenciado pelo framework e pode ser privado ou compartilhado."

Caso em seu aplicativo, você queria armazenar dados pequenos do usuário, o SharedPreferences é uma excelente opção. Como especificado na documentação, 
trata-se de um objeto formado pelo par chave-valor. Para aqueles que já manipularam HashMap na linguagem Java, estarão familiarizados com a estrutura.

Referências do texto entre aspas: 

- GOOGLE DEVELOPERS. Salvar dados chave-valor. Disponível em: <https://developer.android.com/training/data-storage/shared-preferences>. 
Acessado em: 23 de ago. 2024. 

Exemplos práticos

- activity_main.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:layout_margin="16dp"
    tools:context=".MainActivity">
    <EditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/editTextNome"
        android:textAppearance="@style/TextAppearance.AppCompat.Medium"
        android:hint="Digite seu nome:"/>
    <Button
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/buttonNext"
        android:onClick="clicar"
        android:text=">>"
        android:textAppearance="@style/TextAppearance.AppCompat.Medium"
        />
</LinearLayout>

- activity_segunda.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:layout_margin="10dp"
    tools:context=".SegundaActivity">
    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:text="Text"
        android:textAppearance="@style/TextAppearance.AppCompat.Medium"
        android:id="@+id/textViewNome"/>
    <ListView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@color/teal_200"
        android:id="@+id/listViewCores"/>
</LinearLayout>

- activity_terceira.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/layout"
    tools:context=".TerceiraActivity">
</androidx.constraintlayout.widget.ConstraintLayout>

- MainActivity.java
[source,java]
import androidx.appcompat.app.AppCompatActivity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
public class MainActivity extends AppCompatActivity {
    private EditText editTextNome;
    private Button buttonNext;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        editTextNome = findViewById(R.id.editTextNome);
        buttonNext = findViewById(R.id.buttonNext);
    }//onCreate
    public void clicar(View view) {
        Intent intent = new Intent(this, SegundaActivity.class);
        intent.putExtra("nome_usuario",editTextNome.getText().
                toString());
        startActivity(intent);
    }//clicar
}//class

- SegundaActivity.java
[source,java]
import androidx.appcompat.app.AppCompatActivity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;
public class SegundaActivity extends AppCompatActivity
        implements AdapterView.OnItemClickListener {
    private TextView textViewNome;
    private String[] cores = {"Verde","Vermelha","Azul"};
    private ListView listViewCores;
    private ArrayAdapter<String> adapter;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_segunda);
        textViewNome = findViewById(R.id.textViewNome);
        listViewCores = findViewById(R.id.listViewCores);
        Intent intent = getIntent();
        String nome_usuario = intent.getStringExtra("nome_usuario");
        textViewNome.setText(nome_usuario);
        adapter = new ArrayAdapter<>(getApplicationContext(),
                android.R.layout.simple_list_item_1,cores);
        listViewCores.setAdapter(adapter);
        listViewCores.setOnItemClickListener(this);
    }//onCreate
    @Override
    public void onItemClick(AdapterView<?> adapterView, View view, int i, long l) {
        String escolhido = cores[i];
        gravar(escolhido);
    }//onItemClick
    private void gravar(String escolhido) {
        SharedPreferences sharedPreferences =
                getSharedPreferences("dados",MODE_PRIVATE);
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.putString("nome_usuario",textViewNome.getText().toString());
        editor.putString("cor_usuario",escolhido);
        boolean resposta = editor.commit();
        if(resposta){
            Intent intent = new Intent(this, TerceiraActivity.class);
            startActivity(intent);
        }else{
            Toast.makeText(this,"Não salvo", Toast.LENGTH_LONG).show();
        }
    }//gravar
}//class

- TerceiraActivity.java
[source,java]
import androidx.appcompat.app.AppCompatActivity;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.View;
import android.widget.Toast;
public class TerceiraActivity extends AppCompatActivity {
    private View layout;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_terceira);
        layout = findViewById(R.id.layout);
        ler();
    }//onCreate
    private void ler() {
        SharedPreferences sharedPreferences =
                getSharedPreferences("dados",MODE_PRIVATE);
        if(sharedPreferences.contains("nome_usuario") &&
                sharedPreferences.contains("cor_usuario")){
            Toast.makeText(this,
                    sharedPreferences.getString("nome_usuario","nenhum"),
                    Toast.LENGTH_SHORT).show();
            String cor = sharedPreferences.getString("cor_usuario","Branca");
            setarCor(cor);
        }//if
        else{
            Toast.makeText(this,"Erro no arquivo",Toast.LENGTH_SHORT).show();
        }
    }//ler
    private void setarCor(String cor) {
        switch (cor){
            case "Verde":
                layout.setBackgroundColor(getResources()
                        .getColor(android.R.color.holo_green_light));
                break;
            case "Azul":
                layout.setBackgroundColor(getResources()
                        .getColor(android.R.color.holo_blue_light));
                break;
            case "Vermelha":
                layout.setBackgroundColor(getResources()
                        .getColor(android.R.color.holo_red_light));
                break;
            case "Branca":
                layout.setBackgroundColor(getResources()
                        .getColor(android.R.color.white));
                break;
        }//
    }//setarCor
}//class



