= Fragments

Os fragmentos foram criados com o objetivo de aproveitar todo o espaço disponível em uma atividade. A ideia é dividir a atividade em várias partes. Cada uma dessas partes possui seu próprio layout, clico de vida e necessitam de uma atividade. Conforme consta na documentação oficial, Google Developers (2021), "Um fragmento representa uma parte reutilizável da IU do seu app. Um fragmento define e gerencia o próprio layout, tem o próprio ciclo de vida e pode processar os próprios eventos de entrada. Fragmentos não podem existir por conta própria" .

Referências do texto entre aspas: 

- GOOGLE DEVELOPERS. Fragmentos. Disponível em: <https://developer.android.com/guide/fragments#videos>. Acesso em: 22 de fev. 2022. 

Os fragmentos também possuem um ciclo de vida, sendo que o método mais relevante é o onCreateView que será chamado para criar a interface gráfica personalizada no arquivo de layout especifico do fragmento. O método retorna uma View que representa a raiz do layout do fragmento. Para a activity o fragmento será visto como mais uma view inserida em seu layout.

Exemplos práticos (estático):

- link:um/activity_main.xml[activity_main]

- link:um/MainActivity.java[MainActivity]

- link:um/tela1.xml[tela1]

- link:um/Tela1.java[Tela1]

- link:um/tela2.xml[tela2]

- link:um/Tela2.java[Tela2]

Exemplos práticos (dinâmico):

- link:dois/activity_main.xml[activity_main]

- link:dois/MainActivity.java[MainActivity]

- link:dois/tela1.xml[tela1]

- link:dois/Tela1.java[Tela1]

- link:dois/tela2.xml[tela2]

- link:dois/Tela2.java[Tela2]

Veja que na documentação oficial, clique aqui, que a tag para adicionar o fragmento foi atualizada para 

<androidx.fragment.app.FragmentContainerView>. A mesma tag pode ser usada tanto para adicionar o fragmento via XML como programaticamente. A diferença é que para adicionar via XML, deve ser usado o atributo name, passando o nome da classe java que estende a classe Fragment. Caso deseje adicionar de forma dinâmica use o atributo id. 


Por exemplo: no arquivo activity_main.xml a nova tag  adicionada ficaria assim:


<androidx.fragment.app.FragmentContainerView

   android:layout_width="wrap_content"

   android:layout_height="wrap_content"

   android:id="@+id/tela" />


Na classe MainActivity, coloque o gerenciamento de fragmento no método onCreate.


protected void onCreate(Bundle savedInstanceState) {

   super.onCreate(savedInstanceState);

   setContentView(R.layout.activity_main);


   getSupportFragmentManager().beginTransaction()

           .setReorderingAllowed(true)

           .add(R.id.tela, FragmentActivity.class,null)

           .commit();

}


Neste exemplo, a classe FragmentActivity estende a classe Fragment. Observe que não é mais necessário o método inflate para passar o layout criado. Isto é feito no construtor da classe. 


public class FragmentActivity extends Fragment {

   public FragmentActivity(){

       super(R.layout.tela);

   }


   @Override

   public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {

      // super.onViewCreated(view, savedInstanceState);

   }

}

Exemplos práticos:

- link:tres/activity_main.xml[activity_main]

- link:tres/MainActivity.java[MainActivity]

- link:tres/example_fragment.xml[example_fragment]

- link:tres/ExampleFragment.java[ExampleFragment]


