= Estilos / Temas / Botões Personalizados / Botão Flutuante

O SDK do Android fornece estilos e temas definidos para ser usado em um app. Quando um projeto na IDE é criado um tema já é disponibilizado, mas o desenvolvedor pode optar também criar ou personalizar seus próprios estilos e temas.

Exemplos práticos (Estilos e Temas)

- link:um/activity_main.xml[activity_main]

- link:um/colors.xml[colors]

- link:um/themes.xml[themes]

Você pode aproveitar os recursos de estilização para personalizar as formas dos Buttons. 

Exemplos práticos (Botões Personalizados)

- link:dois/button_custom.xml[button_custom]

- link:dois/theme.xml[theme]

- link:dois/layout.xml[layout]

Segundo a Google Developers (2019), "um botão de ação flutuante (FAB, na sigla em inglês) é um botão circular que aciona a ação principal na IU do seu app." 

Ainda, de acordo com a Google Developers (2021), "Os botões de ação flutuantes são usados para um tipo especial de ação promovida. Eles são diferenciados por um ícone circulado flutuando acima da IU e têm comportamentos de movimento especiais relacionados à transformação, lançamento e transferência do ponto de ancoragem."


Referências do texto entre aspas: 

- GOOGLE DEVELOPERS. Adicionar um botão flutuante. Disponível em: <https://developer.android.com/guide/topics/ui/floating-action-button?hl=pt-br>. Acesso em: 22 fev. 2023.

- GOOGLE DEVELOPERS.FloatingActionButton. Disponível em: <https://developer.android.com/reference/com/google/android/material/floatingactionbutton/FloatingActionButton?hl=pt-br>. Acesso em: 22 fev. 2023.

Adicionar o botão flutuante em seu projeto, é uma tarefa simples. Para adicionar a tag <com.google.android.material.floatingactionbutton.FloatingActionButton /> juntamente com alguns atributos no arquivo de xml de layout. E depois usar a classe FloatingActionButton em uma classe .java.

Exemplos práticos (Botão Flutuante)

- link:tres/activity_main.xml[activity_main]

- link:tres/MainActivity.java[MainActivity]
