//caminho padrão para imagens

:figure-caption: Figura
:doctype: book

//gera apresentacao
//pode se baixar os arquivos e add no diretório
:revealjsdir: https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.8.0

//GERAR ARQUIVOS
//make slides
//make ebook

== Exemplos práticos (App Lanchonete)

- MainActivity.java
[source,java]
package com.example.app_lanchonete;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.appcompat.app.AppCompatActivity;
public class MainActivity extends AppCompatActivity {
    private ImageView imageViewBolo, imageViewCafe;
    private Button buttonCalcular;
    private TextView textViewResultado;
    private double valores;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        imageViewBolo = findViewById(R.id.imageBolo);
        imageViewCafe = findViewById(R.id.imageCafe);
        buttonCalcular = findViewById(R.id.btCalcular);
        textViewResultado = findViewById(R.id.textViewResultado);
        Intent intent = getIntent();
        if (intent != null) {
            double valor = intent.getDoubleExtra("total", 0);
            // double valorBolo = intent.getDoubleExtra("totalBolo", 0);
            valores = valores + valor;
        }
    }
    public void escolher(View view) {
        if (R.id.imageBolo == view.getId()) {
            Intent intentBolo = new Intent(getApplicationContext(), ActivityBolo.class);
            if (valores != 0) {
                intentBolo.putExtra("valores", valores);
            }
            startActivity(intentBolo);
        }
        if (R.id.imageCafe == view.getId()) {
            Intent intentCafe = new Intent(getApplicationContext(), ActivityCafe.class);
            if (valores != 0) {
                intentCafe.putExtra("valores", valores);
            }
            startActivity(intentCafe);
        }
        if (R.id.btCalcular == view.getId()) {
            textViewResultado.setText(String.valueOf(valores));
        }
    }
}//class
- ActivityCafe.java
[source,java]
package com.example.app_lanchonete;
import androidx.appcompat.app.AppCompatActivity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
public class ActivityCafe extends AppCompatActivity {
    private EditText editTextQuantidadeCafe;
    private Button buttonCafe;
    private Double valores;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_cafe);
        editTextQuantidadeCafe = findViewById(R.id.editTextQuantidadeCafe);
        buttonCafe = findViewById(R.id.buttonCafe);
        Intent intent = getIntent();
        if (intent != null){
            valores = intent.getDoubleExtra("valores", 0);
        }
    }
    public void clicar(View view){
        int unidade = Integer.parseInt(editTextQuantidadeCafe.getText().toString());
        double total = (unidade * 2.50);
        Intent intent  = new Intent(getApplicationContext(), MainActivity.class);
        valores = valores + total;
        intent.putExtra("total", valores);
        startActivity(intent);
    }//
}
- ActivityBolo.java
[source,java]
package com.example.app_lanchonete;
import androidx.appcompat.app.AppCompatActivity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
public class ActivityBolo extends AppCompatActivity {
    private EditText editTextQuantidadeBolo;
    private Button buttonAdicionar;
    private Double valores;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_bolo);

        editTextQuantidadeBolo = findViewById(R.id.editTextQuantidadeBolo);
        buttonAdicionar = findViewById(R.id.buttonAdicionar);
        Intent intent = getIntent();
        if (intent != null){
            valores = intent.getDoubleExtra("valores", 0);
        }
    }
    public void clicar(View view){
        int unidade = Integer.parseInt(editTextQuantidadeBolo.getText().toString());
        double total = (unidade * 4.50);
        Intent intent = new Intent(getApplicationContext(), MainActivity.class);
        valores = valores + total;
        intent.putExtra("total", valores);
        startActivity(intent);
    }
}
- activity_main.xml
[source,xml]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_margin="10dp"
    android:orientation="vertical" tools:context=".MainActivity">
    <TextView
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:gravity="center"
        android:text="@string/card_pio"
        android:textAppearance="@style/TextAppearance.AppCompat.Large"/>
    <TableLayout android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <TableRow android:layout_width="match_parent"
            android:layout_height="wrap_content">
            <ImageView android:id="@+id/imageCafe"
                android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:onClick="escolher"
                android:src="@drawable/xicara_de_cafe"/>
            <ImageView android:id="@+id/imageBolo"
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1"
                android:onClick="escolher"
                android:src="@drawable/bolo"/>
        </TableRow>
        <TableRow
            android:layout_width="match_parent"
            android:layout_height="wrap_content">
            <TextView android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:background="@color/ciano50"
                android:gravity="center"
                android:text="@string/caf"
                android:textAppearance="@style/TextAppearance.AppCompat.Medium"/>
            <TextView android:layout_width="0dp"
                android:layout_height="wrap_content"
                android:layout_weight="1"
                android:background="@color/amarelo50"
                android:gravity="center"
                android:text="@string/bolo"
                android:textAppearance="@style/TextAppearance.AppCompat.Medium"/>
        </TableRow>
        <LinearLayout android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:orientation="vertical">
            <Button android:id="@+id/btCalcular"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:onClick="escolher"
                android:text="Calcular"/>
            <TextView android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:id="@+id/textViewResultado"/>
        </LinearLayout>
    </TableLayout>
</LinearLayout>
   
- activity_cafe.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:layout_margin="20dp"
    tools:context=".ActivityCafe">
    <TextView
        android:id="@+id/textView"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:background="#A8FF9800"
        android:layout_marginTop="32dp"
        android:gravity="center"
        android:text="Valor da Unidade:R$2,50"
        android:textAppearance="@style/TextAppearance.AppCompat.Medium"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
    <EditText
        android:id="@+id/editTextQuantidadeCafe"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="16dp"
        android:layout_marginTop="32dp"
        android:layout_marginEnd="16dp"
        android:hint="digite a quantidade: "
        android:textAppearance="@style/TextAppearance.AppCompat.Medium"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView"/>
    <Button
        android:id="@+id/buttonCafe"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:onClick="clicar"
        android:text="Adicionar"
        android:layout_marginStart="16dp"
        android:layout_marginTop="32dp"
        android:layout_marginEnd="16dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/editTextQuantidadeCafe" />
</androidx.constraintlayout.widget.ConstraintLayout>
- activity_bolo.xml
[source,xml]
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".ActivityBolo">
    <TextView
        android:id="@+id/textView2"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="32dp"
        android:background="#A8FF9800"
        android:gravity="center"
        android:text="Valor da Unidade:R$4,50"
        android:textAppearance="@style/TextAppearance.AppCompat.Medium"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />
    <EditText
        android:id="@+id/editTextQuantidadeBolo"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginStart="16dp"
        android:layout_marginTop="32dp"
        android:layout_marginEnd="16dp"
        android:hint="digite a quantidade: "
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView2"/>
    <Button
        android:id="@+id/buttonAdicionar"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginStart="16dp"
        android:layout_marginTop="32dp"
        android:layout_marginEnd="16dp"
        android:onClick="clicar"
        android:text="Adicionar"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/editTextQuantidadeBolo" />
</androidx.constraintlayout.widget.ConstraintLayout>


